target: core.trainer.Trainer
params: 
  label: CAMixerSR

  model_config: 
    target: core.arch.CAMixerSR.CAMixerSR
    params: 
      sr_scale: 4
      ratio: 0.5

  optimizer_config: 
    target: torch.optim.AdamW
    params: 
      lr: 0.0001
      weight_decay: 0.0001
      betas: [0.9, 0.999]

  scheduler_config: 
    target: torch.optim.lr_scheduler.MultiStepLR
    params: 
      milestones: [2500, 4000, 4500, 4750]
      gamma: 0.5

  loss_group_config: 
    target: core.arch.CAMixerSR.CAMixerSRLoss

  device: cuda:0