target: core.trainer.Trainer
params: 
  label: RepRFN

  model_config: 
    target: core.arch.RepRFN.RepRFN
    params: 
      in_channels: 3
      out_channels: 3
      feature_nums: 48
      sr_scale: 4
      deploy: false

  optimizer_config: 
    target: torch.optim.AdamW
    params: 
      lr: 0.0001
      weight_decay: 0.0001
      betas: [0.9, 0.999]

  scheduler_config: 
    target: torch.optim.lr_scheduler.StepLR
    params: 
      step_size: 10000  # unuse
      gamma: 0.98

  loss_group_config: 
    target: core.arch.RepRFN.RepRFNLoss

  device: cuda:0