# sequence       : ..., t_-2, t_-1,  t_0,  t_1,  t_2, ...
# anti-alias (gt): ..., null, null,    √,    √,    √, ...
# alias (input)  : ...,    √,    √,    √,    √,    √, ...
# buffers        : ...,    √,    √,    √,    √,    √, ...
# velocity       : ...,  null,   √,    √,    √,    √, ...
# basenames      : ...,  null, null,   √,    √,    √, ...